set(RISCV_TOOLCHAIN_DIR             ${CMAKE_CURRENT_SOURCE_DIR}/../riscv_toolchain)
set(RISCV_TOOLCHAIN_VER_DIR_NAME    RISC-V_Embedded_GCC12)
set(RISCV_COMPILER_TRPILET          riscv-none-elf)
set(RISCV_OPENOCD_PATH              ${RISCV_TOOLCHAIN_DIR}/OpenOCD/bin)

set(RISCV_C_COMPILER        ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/bin/${RISCV_COMPILER_TRPILET}-gcc)
set(RISCV_CXX_COMPILER      ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/bin/${RISCV_COMPILER_TRPILET}-g++)
set(RISCV_LINKER            ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/bin/${RISCV_COMPILER_TRPILET}-ld)
set(RISCV_OBJCOPY           ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/bin/${RISCV_COMPILER_TRPILET}-objcopy)
set(RISCV_AR                ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/bin/${RISCV_COMPILER_TRPILET}-ar)
set(RISCV_ASSEMBLER         ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/bin/${RISCV_COMPILER_TRPILET}-gcc)
set(RISCV_SIZE              ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/bin/${RISCV_COMPILER_TRPILET}-size)
set(RISCV_COMPILER_INCLUDES ${RISCV_TOOLCHAIN_DIR}/${RISCV_TOOLCHAIN_VER_DIR_NAME}/${RISCV_COMPILER_TRPILET}/include)

set(CMAKE_C_COMPILER        ${RISCV_C_COMPILER})
set(CMAKE_CXX_COMPILER      ${RISCV_CXX_COMPILER})
set(CMAKE_ASM_COMPILER      ${RISCV_C_COMPILER})

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)